#!/bin/sh
# branch="$(git branch --show-current)"
# if test "${branch}" = "master" -o "${branch}" = "main"; then
#   echo "Cowardly refusing to commit on ${branch} branch."
#   echo "You can delete this pre-hook or do it right."
#   exit 1
# fi
