#!/bin/bash

latest=$(curl -sSL "https://api.github.com/repos/st3w/neo/releases/latest" | jq -r .name)
gh release download "$latest"

export LDFLAGS="-L/opt/homebrew/opt/ncurses/lib"
export CPPFLAGS="-I/opt/homebrew/opt/ncurses/include"

tar xzf neo*.tar.gz
cd neo-* || exit
./configure
make
sudo make install
