#!/bin/sh

exec brew install coreutils binutils diffutils ed findutils gawk gnu-indent gnu-sed gnu-tar gnu-which gnutls grep gzip screen tmux watch wdiff curl wget bash m4 make file-formula git less openssh python rsync unzip vim gpg jq bash lynx golang gpg kubectl gh pandoc nmap utm shellcheck shfmt helm entr mods weechat bash-completion twitch-cli minikube yt-dlp lolcat figlet yq qemu python

echo "Now don't forget:"
echo "  Add /usr/local/bin/bash to /etc/shells"
echo "  Run chsh -s /usr/local/bin/bash"
echo "  Use #!/usr/bin/env bash as shebang line"
