#!/bin/sh

ln -sf "$PWD/bashrc" "$HOME/.bashrc"
ln -sf "$PWD/shell.d" "$HOME/.shell.d"
ln -sf "$PWD/dircolors/dircolors" "$HOME/.dircolors"
ln -sf "$PWD/inputrc" "$HOME/.inputrc"
ln -sf "$PWD/profile" "$HOME/.profile"

test -d "$HOME/.local/bin" || mkdir -p "$HOME/.local/bin"

for i in vim lynx gh git tmux; do
  cd $i && ./setup
  cd -
done
