#!/bin/sh

# Git-Bash (on Windows) does not have symbolic links (that are worth
# using) so we have to make fresh copies of everything. 
#
# WARNING: running this script will delete and replace the following:

rm "$HOME/.vimrc" 
cp vim/vimrc ~/.vimrc
rm "$HOME/.bashrc" 
cp bashrc ~/.bashrc
rm -r "$HOME/.shell.d" 
cp -r shell.d ~/.shell.d
rm "$HOME/.tmux.conf" 
cp tmux/tmux.conf ~/.tmux.conf

