#!/bin/bash

declare -i major=${BASH_VERSION:0:1}
if [[ ! ( $major == "4" || $major == "5" ) ]]; then
  echo Sorry, requires Bash 4+. Install and try again.
  return
fi

cd ../common/vim && ./setup
cd -
cd ../common/lynx && ./setup
cd -

[[ -d "$HOME/.local/bin" ]] || mkdir -p "$HOME/.local/bin"

if [[ -d "$HOME/.local/bin" ]]; then
  ln -sf "$PWD/../scripts" "$HOME/.local/bin/scripts"
fi

ln -sf "$PWD/bashrc/bashrc" "$HOME/.bashrc"
ln -sf "$PWD/../common/inputrc" "$HOME/.inputrc"
ln -sf "$PWD/../common/fonts" "$HOME/.fonts"
ln -sf "$PWD/../common/profile" "$HOME/.bash_profile"
ln -sf "$PWD/../common/profile" "$HOME/.profile"
ln -sf "$PWD/../common/dircolors/twitch" "$HOME/.dircolors"
ln -sf "$PWD/../common/bin/linux/x86_64/tmux" "$HOME/.local/bin/tmux"
