#!/usr/bin/env bash
set -e

user="containerd"
repo="containerd"

os=$(uname -s)
arch=$(uname -m)
[[ "$arch" == x86_64 ]] && arch=amd64

version=$(curl -sSL "https://api.github.com/repos/$user/$repo/releases/latest" | jq -r .name)
rel="https://github.com/$user/$repo/releases/download/$version/${repo}-${version}-${os,,}-${arch}.tar.gz"

dir=$(mktemp -d)
curl -L "$rel" -o "$dir/$repo.tar.gz"
cd "$dir"
tar Cxzvf /usr/local "$repo.tar.gz"
rm -rf "$dir"
