#!/bin/sh

sudo apt install autoconf build-essentials ncurses-base libncurses5-dev

[ -z "$(command -v gh)" ] && echo "gh required" && exit
latest=$(gh release list --json   tagName -q '.[0].tagName')
gh release download "$latest"

tar xzf neo*.tar.gz
cd neo-* || exit
./configure
make
sudo make install
