#!/bin/bash
set -e

declare version vip interface

vip=192.168.1.200

interface=$(ip -j route | jq -r '.[] | select(.dst == "default") | .dev')

latest_url="https://api.github.com/repos/kube-vip/kube-vip/releases/latest"
version=$(curl -sSL "$latest_url" | jq -r .name)

sudo ctr image pull "ghcr.io/kube-vip/kube-vip:$version"
yaml=$(sudo ctr run --rm --net-host "ghcr.io/kube-vip/kube-vip:$version" \
	vip /kube-vip manifest pod\
	--interface "$interface" \
	--address "$vip" \
	--controlplane \
	--arp \
	--leaderElection)

# https://github.com/kube-vip/kube-vip/issues/684
yaml=${yaml//kubernetes\/admin.conf/kubernetes/super-admin.conf}

sudo tee /etc/kubernetes/manifests/kube-vip.yaml <<< "$yaml"
