#!/bin/sh

sudo apt-install update

sudo apt-get install nmap jq pcregrep lynx make uidmap ruby weechat-curses python-is-python3 libcurses-perl figlet cmatrix build-essential libncurses-dev autoconf entr pip curl bash-completion skopeo buildah postgresql-client-common apt-transport-https ca-certificates curl gpg


sudo cpan -I Term::Animation
