#!/bin/bash
set -e

_install() {
	user="containerd"
	repo="containerd"

	os=$(uname -s)
	arch=$(uname -m)

	[[ "$arch" == x86_64 ]] && arch=amd64

	latest_url="https://api.github.com/repos/$user/$repo/releases/latest"
	version=$(curl -sSL "$latest_url" | jq -r .tag_name)

	tmpdir=$(mktemp -d)
	tar_url="https://github.com/$user/$repo/releases/download/$version/${repo}-${version#v}-${os,,}-${arch}.tar.gz"

	curl -sSL "$tar_url" -o "$tmpdir/$repo.tar.gz"
	sudo tar Cxzvf /usr/local "$tmpdir/$repo.tar.gz"
	rm -rf "$tmpdir"
}

_install
