#!/bin/bash
set -e

OS=$(uname -s)
ARCH=$(uname -m)
[[ "$ARCH" == x86_64 ]] && ARCH=amd64

_install_containerd() {
	latest_url="https://api.github.com/repos/containerd/containerd/releases/latest"
	version=$(curl -sSL "$latest_url" | jq -r .tag_name)
	tmpdir=$(mktemp -d)
	tar_url="https://github.com/containerd/containerd/releases/download/$version/containerd-${version#v}-${OS,,}-${ARCH}.tar.gz"
	curl -sSL "$tar_url" -o "$tmpdir/$repo.tar.gz"
	sudo tar Cxzvf /usr/local "$tmpdir/$repo.tar.gz"
	rm -rf "$tmpdir"
}

_install_service() {
	echo would install service
	sudo curl -sSL "https://raw.githubusercontent.com/containerd/containerd/main/containerd.service" -o /usr/lib/systemd/system/containerd.service
	sudo systemctl daemon-reload
	sudo systemctl enable --now containerd
	sudo systemctl status containerd
}

_install_containerd_cni_plugins() {
	latest="https://api.github.com/repos/containernetworking/plugins/releases/latest"
	version=$(curl -sSL "$latest" | jq -r .tag_name)
	release="https://github.com/containerd/containerd/releases/download/$version/cni-plugins-${OS,,}-${ARCH}-${version}.tar.gz"
	tmpdir=$(mktemp -d)
	curl -sSL "$release" -o "$tmpdir/cni-plugins.tar.gz"
	sudo tar Cxzvf /opt/cni/bin "$tmpdir/cni-plugins.tar.gz"
	rm -rf "$tmpdir"
}

_install_containerd_bash_completion() {
	sudo curl -sSL https://raw.githubusercontent.com/containerd/containerd/refs/heads/main/contrib/autocomplete/ctr -o /etc/bash_completion.d/ctr
}

_install_runc() {
	latest_url="https://api.github.com/repos/opencontainers/runc/releases/latest"
	version=$(curl -sSL "$latest_url" | jq -r .tag_name)
	sudo curl -sSL "https://github.com/opencontainers/runc/releases/download/$version/runc.amd64" -o /usr/local/bin/runc
	sudo chmod +x /usr/local/bin/runc
	runc --version
}

_install_runc_bash_completion() {
	sudo curl -L https://raw.githubusercontent.com/opencontainers/runc/master/contrib/completions/bash/runc -o /etc/bash_completion.d/runc
}

#_install_containerd
#_install_containerd_service
_install_containerd_cni_plugins
#_install_containerd_bash_completion
#_install_runc
#_install_runc_bash_completion
