#!/bin/bash
set -e

_install_latest() {
	user="opencontainers"
	repo="runc"

	os=$(uname -s)
	arch=$(uname -m)

	[[ "$arch" == x86_64 ]] && arch=amd64

	latest_url="https://api.github.com/repos/$user/$repo/releases/latest"
	version=$(curl -sSL "$latest_url" | jq -r .tag_name)

	sudo curl -sSL "https://github.com/opencontainers/runc/releases/download/$version/runc.amd64" -o /usr/local/bin/runc
	sudo chmod +x /usr/local/bin/runc
	runc --version
}

_install_latest
