#!/bin/sh
set -e

cleanup () {
  rm -rf ./istio-*
}
trap cleanup EXIT

curl -L https://istio.io/downloadIstio | sh -
mkdir -p ~/.local/bin
mv istio-*/bin/istioctl ~/.local/bin
#curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.19.0 TARGET_ARCH=x86_64 sh -

