#!/bin/sh
set -e

VERSION=$(curl -L -s https://dl.k8s.io/release/stable.txt)

curl -fsSL "https://pkgs.k8s.io/core:/stable:/${VERSION}/deb/Release.key" \
	| sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.   k8s.io/core:/stable:/$VERSION/deb/ /" \
	| sudo tee /etc/apt/sources.list.d/kubernetes.list

sudo apt-get update
sudo apt-get install -y kubectl

