#!/bin/bash

if [[ -z "$(which vim)" || -z "$(which vimtutor)" ]]; then
	echo "Warning, doesn't look like you have full Vim version."
fi

ln -sf "$PWD/vimrc" "$HOME/.vimrc"
mkdir -p "$HOME/.vim/autoload"
ln -sf "$PWD/plug.vim" "$HOME/.vim/autoload/plug.vim"
mkdir -p "$HOME/.config/nvim"
ln -sf "$PWD/init.lua" "$HOME/.config/nvim/init.lua"
