#!/bin/sh

if [ -z "$(which vim)" -o -z "$(which vimtutor)" ]; then
  echo Need to install full vim.
  exit 1
fi

ln -sf "$PWD/.vimrc" "$HOME/.vimrc"
mkdir "$HOME/.vim/" "$HOME/.vim/autoload"
ln -sf "$PWD/.vim/autoload/plug.vim" "$HOME/.vim/autoload/plug.vim"

