#!/bin/sh

# WARNING: Do *not* use Node unless you absolutely must.

rel=v13.12.0

download () {
  echo -n "Downloading..."
  wget https://nodejs.org/dist/$rel/node-$rel-linux-x64.tar.xz
  result=$?
  if [ $result -eq 0 ]; then
    echo DOWNLOADED
  else
    echo FAILED
  fi
  return $result
}

verify () {
  echo -n "Verifying..."
  wget https://nodejs.org/dist/$rel/SHASUMS256.txt
  wget https://nodejs.org/dist/$rel/SHASUMS256.txt.sig
  wget https://nodejs.org/dist/$rel/SHASUMS256.txt.sig
  grep node-$relz.tar.gz SHASUMS256.txt | sha256sum -c -
  gpg --keyserver pool.sks-keyservers.net --recv-keys DD8F2338BAE7501E3DD5AC78C273792F7D83545D
  gpg --keyserver pool.sks-keyservers.net --recv-keys 4ED778F539E3634C779C87C6D7062848A1AB005C
  gpg --keyserver pool.sks-keyservers.net --recv-keys B9E2F5981AA6E0CD28160D9FF13993A75599653C
  gpg --keyserver pool.sks-keyservers.net --recv-keys 94AE36675C464D64BAFA68DD7434390BDBE9B9C5
  gpg --keyserver pool.sks-keyservers.net --recv-keys B9AE9905FFD7803F25714661B63B535A4C206CA9
  gpg --keyserver pool.sks-keyservers.net --recv-keys 77984A986EBC2AA786BC0F66B01FBB92821C587A
  gpg --keyserver pool.sks-keyservers.net --recv-keys 71DCFD284A79C3B38668286BC97EC7A07EDE3FC1
  gpg --keyserver pool.sks-keyservers.net --recv-keys 8FCCA13FEF1D0C2E91008E09770F7A9A5AE15600
  gpg --keyserver pool.sks-keyservers.net --recv-keys C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8
  gpg --keyserver pool.sks-keyservers.net --recv-keys DD8F2338BAE7501E3DD5AC78C273792F7D83545D
  gpg --keyserver pool.sks-keyservers.net --recv-keys A48C2BEE680E841632CD4E44F07496B3EB3C1762
  gpg --verify SHASUMS256.txt.sig SHASUMS256.txt
  result=$?
  if [ $result -eq 0 ]; then
    echo VERIFIED
  else
    echo FAILED
  fi
  return $result
}

install () {
  echo -n "Installing..."
  unxz node-$rel-linux-x64.tar.xz
  tar -xvf node-$rel-linux-x64.tar
  rm -rf $HOME/.node
  mv node-$rel-linux-x64 $HOME/.node
  echo "INSTALLED"
  echo 'Add $HOME/.node/bin to your $PATH'
}

clean () {
  rm node-$rel-linux-x64* 2>/dev/null
  rm SHASUMS256* 2>/dev/null
}

#download
#verify
#install
download && verify && install
clean

