#!/bin/sh
set -e
test -n "$BASH_DASHX" && set -x

# ubuntu/debian only
#sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
#sudo apt-add-repository https://cli.github.com/packages
#sudo apt update
#sudo apt install -y gh

# identify release
export V=$(curl -sS "https://api.github.com/repos/cli/cli/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c2-) # FIX the shitty subprocs

if [ -z "${V}" ]; then
  echo Could not determine version.
  exit 1
fi

# fetch release
curl -sSL https://github.com/cli/cli/releases/download/v${V}/gh_${V}_linux_amd64.tar.gz -o gh_${V}_linux_amd64.tar.gz

if [ ! -e "gh_${V}_linux_amd64.tar.gz" ]; then
  echo Could not curl down the release tar ball
  exit 1
fi

# extract
tar xvf gh_${V}_linux_amd64.tar.gz

# install
mkdir -p "${HOME}/.local/bin"
mv gh_${V}_linux_amd64/bin/gh "${HOME}/.local/bin"

# cleanup
rm -rf gh_${V}_linux_amd64 gh_${V}_linux_amd64.tar.gz
