#!/bin/sh
set -e

# If you like packages ...
# curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
# sudo apt-get install apt-transport-https --yes
# echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.li
# st.d/helm-stable-debian.list
# sudo apt-get update
# sudo apt-get install helm

# ... or you can do it directly
cd $(mktemp -d)
curl -fsSL -O https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
#export HELM_INSTALL_DIR="${HOME}/.local/bin"
bash ./get-helm-3
