#!/bin/sh

if ! type docker >/dev/null 2>&1; then
  echo "Install requires Docker to build"
  exit 1
fi

cd $(mktemp -d)
curl -LO https://www.python.org/ftp/python/3.6.9/Python-3.6.9.tar.xz
tar xvf Python-3.6.9.tar.xz
cd Python-3.6.9
docker run --rm -u root -v "$PWD:/mymnt:Z" conanio/gcc10 bash -c "
  apt update;
  cd /mymnt;
  ./configure;
  make -j16; 
"
echo
echo "Build complete."
echo
echo Your stuff is in $(pwd)
echo
bindir="$HOME/.local/bin/linux/x86_64"
mkdir -p "${bindir}"
mv python python3.6
install ./python3.6 "${bindir}"
ls -lh "${bindir}/python3.6"
