#!/bin/sh
set -e
test -n "$BASH_DASHX" && set -x

# No need to get GO111MODULE to on anymore (1.17+)
go get github.com/mikefarah/yq/v4
echo <<EOM
Add the following to your .bashrc (or equivalent):

  source <(kind completion bash)

EOM
