#!/bin/sh
set -e
test -n "$BASH_DASHX" && set -x
cd $(mktemp -d)
pwd
ver=$(curl -sS "https://api.github.com/repos/sharkdp/hyperfine/releases/latest" | jq -r .zipball_url)
test -n "$ver"
ver=${ver##*/}
deb="hyperfine_${ver#v}_amd64.deb"
url="https://github.com/sharkdp/hyperfine/releases/download/$ver/$deb"
curl -sSLO "$url"
sudo dpkg -i ./*.deb
