#!/bin/sh
set -e
test -n "$BASH_DASHX" && set -x
cd $(mktemp -d)
pwd
curl -sSLO https://storage.googleapis.com/golang/getgo/installer_linux
chmod +x installer_linux # it fucking turns my stomach to do this without checksum
./installer_linux
