#!/bin/bash

trap "setterm --cursor on; stty echo; trap -- - SIGINT SIGTERM" SIGTERM SIGINT

away="[Away Since $(now)]"
chat "$away"
twitch title "$away"
echo "$away" > ~/.tmux-live-right
pomo stop
fishies
topics
topic="$(tail -1 ~/.topics)"
chat "[Back to '$topic']"
twitch title "$topic"
keyon
