#!/bin/sh
# Prints seconds since first argument was last modified (not created)
path="$1"
if ! test -e "$path"; then
	echo 'usage: ageof <path>'
	exit 1
fi
current=$(date +%s)
ofpath=$(date -r "$path" +%s)
echo $((current - ofpath))
