#!/usr/bin/env perl
use v5.36;
my $what = join ' ', @ARGV;
$what ||= 'in a bit';
`prepend ~/.currently "💤 $what"`;
my @files = grep { -f && /^banner\S/ } glob("*");
my $file  = $files[ int( rand( scalar(@files) ) ) ];
exec "$file back $what"
