#!/bin/sh

# Uses Weechat to ban a target on Twitch.

if [ -z "$TWITCH_USER" ]; then
  echo '$TWITCH_USER environment variable not set.'
  exit 1
fi

if [ -z "$1" -o -z "$2" ]; then
  echo 'usage: ban <twitchid> <reason>'
  exit 1
fi

wee "/msg $TWITCH_USER /ban $1 $2"

