#!/usr/bin/env perl
use v5.36;
use File::Basename;

# TODO check for figl and lolcat deps

not `command -v figl` and say 'figl not found' and exit 1;

__END__

my $clear  = "[2J";
my $curoff = "[?25l";
my $curon  = "[?25h";
my $top    = "[H";
my $lines  = `tput lines` - 6;

my $what = join ' ', @ARGV;

if ( not $what ) {
    print "Text: ";
    $what = <STDIN>;
    chomp $what;
}

sub cleanup {
    print "$curon$clear";
    exit 0;
}

$SIG{'INT'}  = \&cleanup;
$SIG{'TERM'} = \&cleanup;

print $clear. $curoff;
while (1) {
    print $top. `echo "$what" | figl | lolcat -f`;
    sleep 1;
}
