#!/usr/bin/env bash
what="$*"
if [ -z "${what}" ]; then
  read -p "Text: " what
fi
lines=$(tput lines)
pomo stop
tmux split-window \; resize-pane -y $((lines-6)) \; send -t 1 "banner \"$what\"" Enter \; send -t 2 "neo" Enter
