#!/usr/bin/env perl
use v5.36;
use File::Basename;

not `command -v figl` and say 'figl not found' and exit 1;
not `command -v lolcat` and say 'lolcat not found' and exit 1;

my $clear  = "[2J";
my $curoff = "[?25l";
my $curon  = "[?25h";
my $top    = "[H";

my $what = join ' ', @ARGV;
if ( not $what ) {
    print "Text: ";
    $what = <STDIN>;
    chomp $what;
}

sub cleanup {
    print "$curon$clear";
    exit 0;
}
$SIG{'INT'}  = \&cleanup;
$SIG{'TERM'} = \&cleanup;

print $clear. $curoff;
while (1) {
    print $top. `echo "$what" | figl | lolcat -f`;
    sleep 1;
}
