#!/usr/bin/env perl
use v5.36;

my $black   = "[30m";
my $red     = "[31m";
my $green   = "[32m";
my $yellow  = "[33m";
my $blue    = "[34m";
my $magenta = "[35m";
my $cyan    = "[36m";
my $white   = "[37m";
my $blink   = "[5m";
my $reset   = "[0m";

my $what = join ' ', @ARGV;

if ( not $what ) {
    print "Text: ";
    $what = <STDIN>;
    chomp $what;
}

__END__

# requires WHAT
banner() {

	trap 'printf "$curon$clear"; exit; trap -- - SIGINT SIGTERM' TERM INT

	printf "%s" "$clear"

	while true; do
		printf "%s" "$top"
		echo "$WHAT" | figl | lolcat
		printf "%s" "$curoff"
		sleep 2
	done

}

script=$(basename "$0")
case "$script" in
banner) banner "$@" ;;
esac

exit

lines=$(tput lines)
tmux split-window
tmux resize-pane -y $((lines - 6))
tmux send -t 1 "banner \"$what\"" Enter
sleep 1
tmux send -t 2 "fishies" Enter
