#!/usr/bin/env bash
what="$*"
if [ -z "${what}" ]; then
  read -p "Text: " what
fi
cols=$(tput lines)
pomo stop
tmux split-window \; resize-pane -y $((cols-6)) \; send -t 1 "banner \"$what\"" Enter \; send -t 2 "pylights" Enter
