#!/bin/sh
#my $script = basename($0);
#my ($proggy) = $script =~ /^banner(\S+)/;

what="$*"
if [ -z "${what}" ]; then
	echo "Text: "
	read -r what
fi
lines=$(tput lines)
tmux split-window
tmux resize-pane -y $((lines - 6))
tmux send -t 1 "banner \"$what\"" Enter
sleep 1
tmux send -t 2 "neo" Enter
