#!/bin/sh
#my $script = basename($0);
#my ($proggy) = $script =~ /^banner(\S+)/;

what="$*"
if [ -z "${what}" ]; then
	echo "Text: "
	read -r what
fi
lines=$(tput lines)
if type pomo 2>/dev/null; then
	pomo stop
fi
tmux split-window \; resize-pane -y $((lines - 6)) \; send -t 1 "banner \"$what\"" Enter \; sleep 1 \; send -t 2 "neo" Enter
