#!/bin/sh

# TODO optimize rather than brute force
mark='// NEW POST HERE'

markfound=$(grep "$mark" docs/index.adoc)
if [ -z "$markfound" ]; then
	echo "no docs/index.adoc with '$mark' found"
	exit 1
fi

file="$(slug "$*").adoc"

hasfile=$(grep 'include::./'"$file"'\[\]' docs/index.adoc)
if [ -z "$hasfile" ]; then
	perl -p -i -e "s,$mark,$mark\n\ninclude::./$file\[\]," docs/index.adoc
fi

if [ ! -e docs/"$file" ]; then
	printf "= %s\n\n" "$*" >"docs/$file"
fi

exec "$EDITOR" "docs/$file"
