#!/bin/sh

# Just a version of calendar that I prefer.
# 
#     January 2021      
# Su     3 10 17 24 31
# Mo     4 11 18 25   
# Tu     5 12 19 26   
# We     6 13 20 27   
# Th     7 14 21 28   
# Fr  1  8 15 22 29   
# Sa  2  9 16 23 30   
#     1  2  3  4  5  6

#ncal -M -w $*
ncal -w $*

