#!/usr/bin/env perl
use v5.36;
use File::Basename;
use Cwd;

sub get_file {
}

my $statedir = $ENV{XDG_STATE_HOME} || $ENV{HOME} . '/.local/state';
$statedir .= '/changed';
`mkdir -p "$statedir"`;

my $dir  = shift || cwd();
my $last = $statedir . '/' . `slugify "$dir"`;
chomp($last);

not -d $dir and die "$dir isn't a directory";
$dir !~ m,/$, and $dir = $dir . '/';

my $out;
if ( not -e "$last" ) {
    $out = `find "$dir" -type f -not -path '*testdata*'`;
}
else {
    $out = `find "$dir" -newer "$last" -type f -not -path '*testdata*'`;
}
$out =~ s,//,/,g;
print $out;
`touch "$last"`;
