#!/usr/bin/env bash

clear=$'\033[2J'

trap "setterm --cursor on; echo ${clear}; exit; trap -- - SIGINT SIGTERM" SIGTERM SIGINT

echo "${clear}"
zet view disclaimer
now
setterm --cursor off
while true; do sleep 2; done
