#!/bin/bash

clear=$'\033[2J'
top=$'\033[H'

trap "setterm --cursor on; echo ${clear}; exit; trap -- - SIGINT SIGTERM" SIGTERM SIGINT

echo "${clear}"
while true; do
  echo "${top}"
  setterm --cursor off
  echo -e "$@" | figl
  setterm --cursor off
  sleep 2
done
