#!/usr/bin/env perl
use strict;
use warnings;

my $input = shift;
my $delim = shift || '\s+';
my @nums;

if ($input) {
    for my $chunk ( split /,/, $input ) {
        if ( $chunk =~ /^(\d+)\.\.(\d+)$/ ) {
            push @nums, $1 .. $2;
        }
        elsif ( $chunk =~ /^\d+$/ ) {
            push @nums, $chunk;
        }
        else {
            warn "Skipping invalid chunk: $chunk\n";
        }
    }
}

while (<STDIN>) {
    my @fields = split /$delim/;
    if ( not @nums ) {
        push @nums, 1 .. scalar(@fields);
    }
    my @out = ();
    for my $i (@nums) {
        if ( $i <= scalar(@fields) ) {
            push @out, $fields[ $i - 1 ];
        }
    }
    print join( " ", @out ), "\n";
}
