#!/usr/bin/env bash

# Set the figlet default font, font directory, and centering as well as
# defaults to passing it to lolcat for coloring.

figl() {
  #font=${FIGL_FONT:-ansi-shadow}
  font=${FIGL_FONT:-future}
  #font=${FIGL_FONT:-calvin-s}
  #clear
  declare -a buf
  while IFS= read -r line; do
    buf+=("$line")
  done
  #clear
  for line in "${buf[@]}"; do
    figlet -d "$REPOS/github.com/rwxrob/fonts/figlet" -w 72 -f "$font" -c  "${line}" | head -6
  done
}

figl "$*"
