#!/bin/bash

# Set the figlet default font, font directory, and centering as well as
# defaults to passing it to lolcat for coloring.

figl() {
  #font=${FIGL_FONT:-ansi-shadow}
  font=${FIGL_FONT:-future}
  #clear
  declare -a buf
  while IFS= read -r line; do
    buf+=("$line")
  done
  #clear
  for line in "${buf[@]}"; do
    figlet -d "$HOME/.local/share/fonts/figlet" -f "$font" -c -t "${line}" | head -6 | lolcat
  done
}

figl $*
