#!/bin/sh

url="$1"
echo "![WIP](https://img.shields.io/badge/status-wip-red)"
echo "[![GoDoc](https://godoc.org/$url?status.svg)](https://godoc.org/$url)"
echo "[![Go Report Card](https://goreportcard.com/badge/$url)](https://goreportcard.com/report/$url)"
echo "[![Coverage](https://gocover.io/_badge/$url)](https://gocover.io/$url)"
echo
