#!/usr/bin/env bash

#url="https://chatgpt.com?q=$(urlencode "$*")"
#open "$url"

_have() { type "$1" &>/dev/null; }
! _have mods && echo "requires charmbracelet/mods" && exit 1
# OPEN_API_KEY=$(<~/.config/gpt/key)
mods --continue-last "$*"
