#!/bin/bash

# Starts up an nginx server in a docker container on localhost enabling
# dual-streaming to YouTube and Twitch at the same time. Requires an
# auth script or app that returns the private streamkeys as well as the
# local RTMP secret to be added to OBS. Requires running as root.

startd () {
  local twitch="rtmp://live-jfk.twitch.tv/app/$(auth token twitchstream)"
  local youtube="rtmp://a.rtmp.youtube.com/live2/$(auth token youtubestream)"
  local secret="$(auth token rtmpsecret)"
  sudo docker run --rm -t -p 1935:1935 -p 443:443 --name gstreamd \
    -e STREAMS="$youtube;$twitch"\
    -e PASSWORD="$secret" \
    -e RTMPSECRET="$secret" \
    blaize/nginx-rtmp &
}

stopd () {
  sudo docker stop gstreamd
}

case $1 in
  start)  startd ;;
  stop)  stopd ;;
  *) echo "usage: gstreamd (start|stop)"; exit 1 ;;
esac
