#!/bin/sh
chart="$1"
version="$2"
if test -z "$chart" || test -z "$version"; then
	echo "usage: $0 CHART APP_VERSION"
	exit 1
fi
helm search repo "$chart" -o json --versions |
	jq -r ".[] | select(.app_version == \"$version\") | .version"
