#!/bin/bash

if [[ "$OSTYPE" =~ ^(darwin|bsd) ]]; then
	if [[ -z "$1" ]]; then
		date "+# LOG%Y%m%d%H%M%S: %A, %B %e, %Y, %l:%M:%S%p %Z"
	else
		date -v"$*" "+# LOG%Y%m%d%H%M%S: %A, %B %e, %Y, %l:%M:%S%p %Z"
	fi
	exit
fi

if [[ -z "$1" ]]; then
	date "+# LOG%Y%m%d%H%M%S: %A, %B %e, %Y, %l:%M:%S%p %Z"
else
	date "+# LOG%Y%m%d%H%M%S: %A, %B %e, %Y, %l:%M:%S%p %Z" -d "$*"
fi
