#!/bin/bash

# Produces a centered title in the middle of a horizontal rule of text.

str=$(argsorin $*)
len=${#str}
side=$((((HRULEWIDTH / 2) - len / 2) - 3))
left=$side
right=$side
[[ $((len % 2)) == 1 ]] && right=$((right - 1))
echo "# $(echon '-' $left) $str $(echon '-' $right)"
