#!/bin/sh

# Creates a log entry with an isosec unique directory name within the
# $KN/log parent directory. Edits with $EDITOR or vim. Prompts to commit
# using the first 50 characters of the first line (ignoring heading
# hashtags if prefixed). Git Pushes. Designed to be used in situations
# where commiting and pushing to main/master is allowed.

set -e
dir="$KN/log/$(isosec)"
mkdir -p "$dir"
${EDITOR:-vim} "$dir/README.md"
read -p 'Do you want to commit? ' a
test "$a" = y -o "$a" = yes
cd "$dir"
line=$(head -1 "$dir/README.md")
line=$(echo "${line#* }" | cut -c1-50)
echo "Adding: $line"
git add -A "$dir"
git commit -m "$line"
git push
