#!/bin/sh

# Opens the default log file with the default EDITOR. Accepts the
# standard `date` offset

relpath=$(datepath "$*")
dir="${KNPATH}/log/$relpath"
file="$dir/README.md"
mkdir -p "${dir}"

# prepend a timestamped heading

tmpfile=$(mktemp)
hnow "$*" > "${tmpfile}" 
echo -n "\n\n\n">> "${tmpfile}"
if [ -e "${file}" ];then
  cat "${file}" >> "${tmpfile}"
fi
mv "${tmpfile}" "${file}"

echo "${file}"
vim +3 "${file}"

cd "${dir}"
git add "${file}" 
git commit
git push
