#!/bin/sh
branch="$1"
if [ -z "${branch}" ]; then
    branch=$(git branch --show-current)
fi
if [ -z "${branch}" ]; then
    echo "no branch detected"
    exit 1
fi
git switch main && git merge "${branch}" && git push -u origin main && git branch -d "${branch}"
