#!/usr/bin/env bash

test ! -n "${SCRIPTS}"  && echo "SCRIPTS not set" && exit 1;
test ! -n "${1}"  && echo "usage: newscript <name>" && exit 1;

path="${SCRIPTS}/${1}"

if test -e "${path}"; then
  read -p "${1} already exists. Edit? " yes
  case "${yes}" in
    y|yes|yep|yeppers|yeah|ok|okay) exec "$EDITOR" "${path}"
  esac
  exit 0
fi

printf "#!/bin/sh\n\n" > "${path}"
chmod +x "${path}" 
exec "$EDITOR" +2 "${path}"
