#!/bin/bash

# Opens the default quotes file with vim. Prompts to commit.

rel="$1"
dir="${KN}/notes/${rel}"
file="${dir}/README.md"
mkdir -p "${dir}"
vim "${file}"

read -p 'Do you want to commit? ' commit

if [[ ! $commit =~ ^[Yy] ]]; then
  exit
fi

cd "${dir}"
git add "${file}" 
git commit
git push
