#!/bin/bash

if [[ "$OSTYPE" =~ ^(darwin|bsd) ]]; then
	if [[ -z "$1" ]]; then
		date "+%A, %B %e, %Y, %l:%M:%S%p %Z" | perl -pe 's, +, ,g'
	else
		date -v"$*" "+%A, %B %e, %Y, %l:%M:%S%p %Z" | perl -pe 's, +, ,g'
	fi
	exit
fi

if [[ -z "$1" ]]; then
	date "+%A, %B %e, %Y, %l:%M:%S%p %Z" | perl -pe 's, +, ,g'
else
	date "+%A, %B %e, %Y, %l:%M:%S%p %Z" -d "$*" | perl -pe 's, +, ,g'
fi
