#!/bin/bash

if [[ "$OSTYPE" =~ ^(darwin|bsd) ]]; then
	if [[ -z "$1" ]]; then
		out=$(date "+%A, %B %e, %Y, %l:%M:%S%p %Z")
	else
		out=$(date -v"$*" "+%A, %B %e, %Y, %l:%M:%S%p %Z")
	fi
	echo "${out//  / }"
	exit
fi

if [[ -z "$1" ]]; then
	out=$(date "+%A, %B %e, %Y, %l:%M:%S%p %Z")
else
	out=$(date "+%A, %B %e, %Y, %l:%M:%S%p %Z" -d "$*")
	echo "${out//  / }"
fi
