#!/bin/bash

if [[ $OSTYPE =~ ^(darwin|bsd) ]]; then
	if [[ -z "$1" ]]; then
		out=$(date "+%a %b %e %Y %l:%M%p %Z")
	else
		out=$(date -v"$*" "+%a %b %e %Y %l:%M%p %Z")
	fi
	echo "${out//  / }"
	exit
fi

if [[ -z "$1" ]]; then
	out=$(date "+%a %b %e %Y %l:%M%p %Z")
else
	out=$(date "+%a %b %e %Y %l:%M%p %Z" -d "$*")
	echo "${out//  / }"
fi
