#!/usr/bin/env bash

in-repo() {
	git rev-parse --count HEAD >/dev/null 2>&1
	return $?
}

has-local-changes() {
	test -n "$(git status --porcelain)"
	return $?
}

gitsave() {
	git pull
	git add -A .
	local message="$*"
	message=${message,,}
	if test -n "$message"; then
		git commit -a -m "$message"
	elif test -e /tmp/commitmsg; then
		git commit -a -F /tmp/commitmsg
		mv /tmp/commitmsg "/tmp/commitmsg.$(date +%s)"
	else
		git commit -a -m "save"
	fi
	if type push; then
		push
	else
		git push
	fi
}

main() {
	if ! in-repo; then
		echo "Not in a repo."
		return 1
	fi
	if ! has-local-changes; then
		echo "Already at the latest."
		return 0
	fi
	gitsave "$@"
	return $?
}

main "$@"
