#!/bin/bash

#-g "420x90+1040+1010" \
#-g "420x90+3120+1010" \
#-g "420x90+2920+1010" \

# best for 79 cols, and cam
#-g "420x90+3000+1010" \
#-g "300x90+3166+1010" \
#--font-color "#FABD2F"

/usr/bin/screenkey \
  --persist \
  -t 4 \
  --compr-cnt 1 \
  -p fixed \
  -g "500x100+3100+0" \
  -f "UbuntuMono Nerd Font" \
  --font-color "#EBDBB2" \
  --bg-color "#222222" \
  --bak-mode full \
  --opacity 1 &

#--font-color "#d65d0e" \
#  -g "634x40+670+0" \
