#!/bin/bash

#-g "420x90+1040+1010" \
#-g "420x90+3120+1010" \
#-g "420x90+2920+1010" \

# best for 79 cols, and cam
#-g "420x90+3000+1010" \
#-g "300x90+3166+1010" \

/usr/bin/screenkey \
  --persist \
  -t 4 \
  -p fixed \
  --compr-cnt 1 \
  -g "500x90+2550+1000" \
  -s large \
  -f "UbuntuMono Nerd Font" \
  --font-color "#fe8019" \
  --opacity 0 &

#--font-color "#d65d0e" \
#  -g "634x40+670+0" \
