#!/bin/sh

# Prints the terminal theme regular colors (and some other escapes). For
# "bright/bold" variation add 1; in front of the number. Useful for
# sampling and remembering the escapes when hardcoding them into scripts
# for portability. Keep in mind that the color names are those given for
# the original color terminal and obviously can vary widely. For color
# intensive output consider shortening the names to their first letter
# instead and don't forget to wrap them within ${}. Omits (and overrides
# any inherited) colors when not interactive/piped.

case "$1" in

shell)
	cat <<EOM
black="[30m"
red="[31m"
green="[32m"
yellow="[33m"
blue="[34m"
magenta="[35m"
cyan="[36m"
white="[37m"
blink="[5m"
reset="[0m"
clear="[2J"
curoff="[?25h"
curon="[?25h"
top="[H"
EOM
	;;

perl)
	cat <<'EOM'
my $black="[30m";
my $red="[31m";
my $green="[32m";
my $yellow="[33m";
my $blue="[34m";
my $magenta="[35m";
my $cyan="[36m";
my $white="[37m";
my $blink="[5m";
my $reset="[0m";
my $clear="[2J";
my $curoff="[?25h";
my $curon="[?25h";
my $top="[H";
EOM
	;;

esac
