#!/bin/bash

# Opens the default todo file with vim. Prompts to commit.

dir="${KN}/todo"
file="${dir}/README.md"
mkdir -p "${dir}"
vim +3 "${file}"

read -p 'Do you want to commit? ' commit

if [[ ! $commit =~ ^[Yy] ]]; then
  exit
fi

cd "${dir}"
git add "${file}" 
git commit -m 'TODOs updated.'
git push
