#!/bin/bash

# Updates YouTube and Twitch Titles, sets the GitHub profile status, and
# sends a tweet pointing to the YouTube video.

# FIXME derive the live youtube video
YOUTUBE_VIDEO=NKfTsd2l7Nc

YOUTUBE_TOKEN=$(auth token youtube)
YOUTUBE_CLIENTID=$(auth get id youtube)
TWITCH_TOKEN=$(auth token twitch)
TWITCH_CLIENTID=$(auth get id twitch)
TWITCH_CHANID=447179030

TOPIC="$*"

set_youtube_title () {
curl -s \
  -X PUT "https://www.googleapis.com/youtube/v3/videos?part=snippet" \
  -H "Client-ID: $YOUTUBE_CLIENTID" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $YOUTUBE_TOKEN" \
  -d '{"id":"'$YOUTUBE_VIDEO'","snippet":{"title":"'"$TOPIC"'","categoryId":"28"}}' \
  > /dev/null &
}

twitch () {
curl -s  \
  -X PUT "https://api.twitch.tv/kraken/channels/$TWITCH_CHANID" \
  -H "Client-ID: $TWITCH_CLIENTID" \
  -H "Authorization: OAuth $TWITCH_TOKEN" \
  -H 'Accept: application/vnd.twitchtv.v5+json' \
  -H 'Content-Type: application/json' \
  -d '{"channel":{"status":"'"$TOPIC"'"}}' \
  > /dev/null &
}

set_irc_topic () {
  ssh skilstak.sh 'echo "*/topic '$TOPIC'" >> .weechat/weechat_fifo' &
}

set_github_status () {
  gh live "$TOPIC" > /dev/null &
}

set_twitter_status () {
  tweet "📺 ${TOPIC} https://youtube.com/${YOUTUBE_VIDEO}"
}

#set_youtube_title
#set_twitch_title
#set_irc_topic
#set_github_status
set_twitter_status
