#!/bin/bash

# Updates YouTube and Twitch Titles, sets the GitHub profile status, and
# sends a tweet pointing to the YouTube video.

# change these do solarized/gruvbox variations (not millions)
if [[ -t 1 ]]; then
  GOLD=$'\033[38;2;184;138;0m'
  RED=$'\033[38;2;255;0;0m'
  GREY=$'\033[38;2;100;100;100m'
  CYAN=$'\033[38;2;0;255;255m'
  GREEN=$'\033[38;2;0;255;0m'
  X=$'\033[0m'
fi

fatal () {
  echo "${RED}$*${X}"
  exit 1
}

topic="$*"
if [[ ${#topic} > 80 ]]; then
  fatal 'Topic must be under 80 characters'
fi

# FIXME derive the live youtube video
YOUTUBE_VIDEO=X90l3OW5Ns4

YOUTUBE_TOKEN=$(auth token youtube)
YOUTUBE_CLIENTID=$(auth get id youtube)
TWITCH_TOKEN=$(auth token twitch)
TWITCH_CLIENTID=$(auth get id twitch)
TWITCH_CHANID=447179030

DESC_FILE="/tmp/vid${YOUTUBE_VIDEO}"

set_youtube_title () {
  local tpl='{"id":"%s","snippet":{"title":"%s","categoryId":"28","description":"%s"}}'
  local desc="$(jsonesc < "$DESC_FILE")"
  echo "$desc"
  local data=$(printf "${tpl}" "${YOUTUBE_VIDEO}" "${topic}" "${desc}")
curl -s \
  -X PUT "https://www.googleapis.com/youtube/v3/videos?part=snippet" \
  -H "Client-ID: $YOUTUBE_CLIENTID" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $YOUTUBE_TOKEN" \
  -d "${data}" \
  > /dev/null &
}

set_twitch_title () {
curl -s  \
  -X PUT "https://api.twitch.tv/kraken/channels/$TWITCH_CHANID" \
  -H "Client-ID: $TWITCH_CLIENTID" \
  -H "Authorization: OAuth $TWITCH_TOKEN" \
  -H 'Accept: application/vnd.twitchtv.v5+json' \
  -H 'Content-Type: application/json' \
  -d '{"channel":{"status":"'"$topic"'"}}' \
  > /dev/null &
}

set_irc_topic () {
  ssh skilstak.sh 'echo "*/topic '$topic'" >> .weechat/weechat_fifo' &
}

set_github_status () {
  if [[ $topic =~ ^\( ]]; then
    gh offline "$topic" > /dev/null &
    return
  fi
  gh live "$topic" > /dev/null &
}

set_twitter_status () {
  if [[ $topic =~ ^\( ]]; then
    return
  fi 
  twitter update "📺 ${topic} https://youtu.be/${YOUTUBE_VIDEO}?t=$(vidoffsetsec)"
}

edit_description () {
  echo -e "$(vidoffset)\n${topic}" >> "${DESC_FILE}"
  ${EDITOR} "${DESC_FILE}"
}

edit_description
set_youtube_title
set_twitch_title
set_irc_topic
set_github_status
set_twitter_status
