#!/bin/sh
name="$1"
test -z "$1" && name=$TWITCH_LOGIN
test -z "$name" && echo "TWITCH_LOGIN or first arg required" && exit 1
vid=$(twitch api get videos -q user_id="$(twitch-id "$name")" | jq -r '.data[0].id')

data=$(echo "$json" | jq -r '.data[]')
test -z "$data" && echo "$name appears offline" && exit 1
echo "$data" | jq -r '.user_login + " • "+.title+"" + " • " + .game_name + " • " + (.viewer_count | tostring) + " viewers"'
