#!/bin/bash
set -e

# If you prefer to not have dependencies on the helper commands for the
# following you can simply set them directly:

TOKEN=$(auth token twitch)
CLIENTID=$(auth get id twitch)
CLIENTSEC=$(auth get secret twitch)
USERID=$(config twitch.id)
TITLE=$(config twitch.title)
LANG=$(config twitch.lang)
GAMEID=$(config twitch.gameid)
GAME=$(config twitch.game)

# Title changes the Title stream info (Go Live notification cannot be
# changed from API). If the special 'default' title is passed it will
# use the output of the `config twitch.title` command. Otherwise, the
# arguments will be combined into a single script and an isosec
# identifier added to the end which is 16 characters plus a space (ex:
# "Title [20210508163250]") Twitch titles have 140 character limit but
# this command limits them to 123 characters since every title will have
# an isosec identifier added to the end which is 16 characters plus
# a space (ex: "Title [20210508163250]")

title() {
  test -z "$1" && echo "$TITLE" && return
  if test "${1%% *}" = default; then
    title="$TITLE"
  else
    if test ${1:0:1} = '['; then
      title="$*"
    else
      title="$* [$(isosec)]"
    fi
  fi
  resp=$(curl -sS -X PATCH "https://api.twitch.tv/helix/channels?broadcaster_id=$USERID" \
    -H "Authorization: Bearer $TOKEN" \
    -H "Client-Id: $CLIENTID" \
    -H 'Content-Type: application/json' \
    --data-raw '{"game_id":"'$GAMEID'", "title":"'"$title"'", "broadcaster_language":"'$LANG'"}' | jq -r '[.status,.message] | @tsv')
}

## ------------------------------- main -------------------------------

command="$1"
test -n "$command" && shift

case "$command" in
title) title "$@" ;;
esac
