#!/bin/sh
name="$TWITCH_LOGIN"
test -z "$name" && name=rwxrob
mark="$1"
test -z "$mark" && mark=mark
twitch api post streams/markers \
	-q user_id="$(twitch-id "$name")" \
	-q description="$*" | jq -r '
		.data[0] | "/me marked \"" + .description + "\" at " + .created_at'
