#!/bin/sh
name="$1"
test -z "$1" && name=$TWITCH_LOGIN
test -z "$name" && echo "TWITCH_LOGIN or first arg required" && exit 1
youtube-dl -F "https://twitch.tv/$name" | pae 'm,^\d+p(\S+)?, and say $&'
