#!/bin/sh

buf="$*"

if test -n "$buf"; then
	echo "*$buf" | toemoji >~/.weechat/fifo
	#tmux -L live send -t 2 "$buf" Enter
	exit
fi

IFS=
while read -r line; do
	echo "*$line" | toemoji >~/.weechat/fifo
	#tmux -L live send -t 2 "$line" Enter
done
