#!/usr/bin/bash

## Environment Dependencies:
##   YOUTUBE_RECORDINGS
##   YOUTUBE_CHANID
##   COMP_LINE
## 
## Script Dependencies
##   auth
##   newest

YOUTUBE_APIKEY=$(auth get id youtubeapikey)

lastid () {
  curl -s "https://www.googleapis.com/youtube/v3/search?part=snippet&key=${YOUTUBE_APIKEY}&channelId=${YOUTUBE_CHANID}&type=video&order=date" | \
  jq -r '.items[0].id.videoId'
}

liveid () {
  curl -s "https://www.googleapis.com/youtube/v3/search?part=snippet&key=${YOUTUBE_APIKEY}&channelId=${YOUTUBE_CHANID}&type=video&eventType=live" | \
  jq -r '.items[0].id.videoId'
}

openlast () {
    open "https://youtu.be/$(lastid)"
}

############################## Main Command  #############################

subcommand="${1-usage}"
shift 2>/dev/null

if [ -z "$subcommand" ]; then
    usage
    exit 1
fi

commands () {
    echo ${commands[@]}
}

archive () {
  echo would archive description file
  # TODO open the $(yt lastid) file for editing
  # TODO check file for a good # heading on first line and empty line
  # TODO create a slug out of title for filename
  # TODO create a <rwxrob>/videos/<year>/<month>/<day> directory if needed
  # TODO mv /tmp/vid* file into directory
  # TODO set final title and description of last video
  # TODO commit changes to <rwxrob> repo
}

elapsed () {
  local video=$(liveid)
  if [[ -z "${video}" ]]; then
    return
  fi
  local epoch=$(date +%s)
  local offset=$(( "${epoch}" - $(stat --printf '%W' $(newest "${vids}"))))
  echo $offset
}

# elapsedsec () {
# }

declare -a commands=(commands liveid lastid openlast elapsed elapsedsec)

for i in ${commands[@]}; do
    if [[ "$i" == "$subcommand" ]]; then
        "$subcommand" "$@"
        exit 0
    fi
done

######################### Tab Completion Context ########################

# remember COMP_LINE is changed by shift
if [ -n "$COMP_LINE" ]; then
    for cmd in ${commands[@]}; do 
        [[ "${cmd:0:${#1}}" == "$1" ]] && echo $cmd
    done
    exit 0
fi
