#!/usr/bin/bash

USER=rwxrob
KEY=$(auth get id youtubeapikey)
ID=UCs2Kaw3Soa63cJq3H0VA7og

liveid () {
  curl -s "https://www.googleapis.com/youtube/v3/search?part=snippet&key=$KEY&channelId=$ID&eventType=live&type=video" | \
  jq -r '.items[0].id.videoId'
}

############################## Main Command  #############################

subcommand="${1-usage}"
shift 2>/dev/null

if [ -z "$subcommand" ]; then
    usage
    exit 1
fi

commands () {
    echo ${commands[@]}
}

declare -a commands=(commands liveid)

for i in ${commands[@]}; do
    if [[ "$i" == "$subcommand" ]]; then
        "$subcommand" "$@"
        exit 0
    fi
done

######################### Tab Completion Context ########################

# remember COMP_LINE is changed by shift
if [ -n "$COMP_LINE" ]; then
    for cmd in ${commands[@]}; do 
        [[ "${cmd:0:${#1}}" == "$1" ]] && echo $cmd
    done
    exit 0
fi
