#!/bin/sh
set -e

# This zet script is a multicall executable, which means you may have
# opened another file or link which opened this.
#
# Add the following to bashrc to enable completion (replace zet with
# your multicall executable name):
#
#   complete -C zet zet
#
# Note that you will need one such complete line for every multicall
# variation of this script (ex: ln -s zet log; complete -C log log)

test -z "$GITUSER" && echo "GITUSER not set." && exit 1

# Check for $ZETDIR or $KN variables (in that order). If found, use
# those variables for the parent directory. If they do not exist, check
# for the existance of the default directory and create the folder if
# necessary. This not only allows for customization of the parent
# directory via $ZETDIR, but also allows for compatibility with the
# KEG/KN toolset.

if test -n "$ZETDIR"; then
  pdir="$ZETDIR"
  echo "$pdir" && exit 1
elif test -n "$KN"; then
  pdir="$KN"
  echo "$pdir" && exit 1
else
  pdir="$HOME/.local/share/zet"
  test ! -d "$pdir" && mkdir -p "$pdir"
  echo "$pdir" && exit 1
fi

EXE=${0##*/}
test -z "$EXE" && echo "Could not determine name of executable." && exit 1

# Add creates a Zettelkasten repo entry with an isosec unique directory
# name within the $KN/$EXE parent directory. Whatever the effective name
# of the executable (multicall, symlink, hardlink, alias, copy) will be
# used for $EXE. Opens editor with $EDITOR or vim.  Git commits using
# the first 50 characters of the first line (ignoring heading hashtags
# if prefixed) and pushes. Designed to be used in situations where
# commiting and pushing to main/master is allowed (which is usually fine
# for knowledge repos).

add() {
  test ! -d "$pdir/$EXE" && echo "Directory not found: $pdir/$EXE" && exit 1
  dir="$pdir/$EXE/$(isosec)"
  mkdir -p "$dir"
  ${EDITOR:-vim} "$dir/README.md"
  cd "$dir"
  test ! -e "$dir/README.md" && rmdir "$dir"
  line=$(head -1 "$dir/README.md" | sed 's/#\+ *//')
  test -n "$line"
  echo "Adding: $line"
  git add -A "$dir"
  git commit -m "$line"
  git push
}

query() {
  test -z "$1" && echo "Missing search query." && exit 1
  type urlencode >/dev/null 2>&1
  term="$*"
  it="https://github.com/$GITUSER/$EXE/search?q=$(urlencode $term)"
  echo "[$term]: <$it>"
  type wee >/dev/null 2>&1 || return 0
  exec wee "$it"
}

case "$1" in
add | "") add ;;
q | query)
  shift
  query "$@"
  ;;
*) echo Unsupported. ;;
esac
