#!/bin/bash
docker pull vagrantlibvirt/vagrant-libvirt:latest
echo ' 
Now add the following function to your ~/.bashrc:

vagrant () 
{ 
  docker run -it --rm  \
  -e LIBVIRT_DEFAULT_URI \
  -v /var/run/libvirt/:/var/run/libvirt/ \
  -v ~/.vagrant.d:/.vagrant.d \
  -v $(realpath "${PWD}"):${PWD} \
  -w $(realpath "${PWD}") \
  --network host \
    vagrantlibvirt/vagrant-libvirt:latest vagrant "$@"
}
'

