#!/bin/sh

# WARNING: This setup requires a custom form of lynx (a shell script in
# scripts) be installed as well as lynx. [For an easier text browsing
# experience that works out of the box use w3m instead.]

# Also have a look at https://github.com/rwxrob/lynx for more.

mkdir ~/.config/ 2>/dev/null
rm -rf ~/.config/lynx 2>/dev/null
ln -s "$PWD" "$HOME/.config/lynx"
ls -l ~/.config/lynx
